{
 "title": "Setup Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "AC - RPM - Rotations Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cluster)(rate(hostlookuper_rotations_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS RPM - Berne",
   "type": "gauge",
   "description": "DNS Entries Rotations (Updates) Per Minute",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "recpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hostlookuper_rotations_total{cluster=\"berne-cluster\"}[10m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Lookups per cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(hostlookuper_dns_lookups_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bern - DNS Lookups",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hostlookuper_dns_lookups_total{cluster=\"berne-cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS RPM - Zurich",
   "type": "gauge",
   "description": "DNS Entries Rotations (Updates) Per Minute",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "recpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hostlookuper_rotations_total{cluster=\"zurich-cluster\"}[10m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zurich - DNS Lookups",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hostlookuper_dns_lookups_total{job=\"hostlookuper-zurich-5gc\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC - Accuracy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(hostlookuper_classification_total{classification=~\"tp|tn\"}[$__rate_interval])) / (sum by(job) (rate(hostlookuper_classification_total[1m])))",
     "legendFormat": "Accuracy {{job}}"
    }
   ]
  },
  {
   "title": "Accuracy of Resolutions per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(hostlookuper_classification_total{classification=~\"tp|tn\"}[$__rate_interval])) / (sum by(job) (rate(hostlookuper_classification_total[1m])))",
     "legendFormat": "Accuracy {{job}}"
    }
   ]
  },
  {
   "title": "Accuracy breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by (classification) (rate(hostlookuper_classification_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC - Probe Latency Percentiles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  rate(hostlookuper_dns_lookup_duration_seconds_sum[1m])\n)\n/\nsum by (cluster) (\n  rate(hostlookuper_dns_lookup_duration_seconds_count[1m])\n)",
     "legendFormat": "Avg Latency {{cluster}}"
    }
   ]
  },
  {
   "title": "Average Probe Latency Per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  rate(hostlookuper_dns_lookup_duration_seconds_sum[1m])\n)\n/\nsum by (cluster) (\n  rate(hostlookuper_dns_lookup_duration_seconds_count[1m])\n)",
     "legendFormat": "Avg Latency {{cluster}}"
    }
   ]
  },
  {
   "title": "Probe Jitter ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "stddev_over_time(\n  (\n    sum by (cluster) (\n      rate(hostlookuper_dns_lookup_duration_seconds_sum[$__rate_interval])\n    )\n    /\n    sum by (cluster) (\n      rate(hostlookuper_dns_lookup_duration_seconds_count[$__rate_interval])\n    )\n  )[1m:]\n)",
     "legendFormat": "Jitter {{cluster}}"
    }
   ]
  },
  {
   "title": "AC - Probe Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{ }[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{ }[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{ }[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Zurich - Probe Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"zurich-cluster\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"zurich-cluster\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"zurich-cluster\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Berne - Probe Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"berne-cluster\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"berne-cluster\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"berne-cluster\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "99th - Probe Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"berne-cluster\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile berne-cluster"
    },
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"zurich-cluster\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile zurich-cluster"
    }
   ]
  },
  {
   "title": "90th - Probe Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"berne-cluster\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile berne-cluster"
    },
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"zurich-cluster\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile zurich-cluster"
    }
   ]
  },
  {
   "title": "50th - Probe Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"berne-cluster\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile berne-cluster"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(hostlookuper_dns_lookup_duration_seconds_bucket{cluster=\"zurich-cluster\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile zurich-cluster"
    }
   ]
  },
  {
   "title": "K8s DNS - All Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(coredns_dns_requests_total{job=\"kube-dns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s DNS - All Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 40 },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(coredns_dns_requests_total{job=\"kube-dns\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC - K8s DNS Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 40 },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  rate(coredns_dns_request_duration_seconds_sum{role=\"kubedns\"}[1m])\n)\n/\nsum by (cluster) (\n  rate(coredns_dns_request_duration_seconds_count{role=\"kubedns\"}[1m])\n)",
     "legendFormat": "Avg Latency {{cluster}}"
    }
   ]
  },
  {
   "title": "K8s DNS Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 40 },
   "targets": [
    {
     "expr": "stddev_over_time(\n  (\n    sum by (cluster) (\n      rate(coredns_dns_request_duration_seconds_sum{job=\"kube-dns\"}[$__rate_interval])\n    )\n    /\n    sum by (cluster) (\n      rate(coredns_dns_request_duration_seconds_count{job=\"kube-dns\"}[$__rate_interval])\n    )\n  )[1m:]\n)",
     "legendFormat": "Jitter {{cluster}}"
    }
   ]
  },
  {
   "title": "Forwarder - All Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(coredns_dns_requests_total{job=\"forwarder\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forwarder - All Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 48 },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(coredns_dns_requests_total{job=\"forwarder\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC - Forwarder DNS Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 48 },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  rate(coredns_dns_request_duration_seconds_sum{role=\"forwarder-dns-server\"}[1m])\n)\n/\nsum by (cluster) (\n  rate(coredns_dns_request_duration_seconds_count{role=\"forwarder-dns-server\"}[1m])\n)",
     "legendFormat": "Avg Latency {{cluster}}"
    }
   ]
  },
  {
   "title": "Forwarder DNS Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 48 },
   "targets": [
    {
     "expr": "stddev_over_time(\n  (\n    sum by (cluster) (\n      rate(coredns_dns_request_duration_seconds_sum{job=\"forwarder\"}[$__rate_interval])\n    )\n    /\n    sum by (cluster) (\n      rate(coredns_dns_request_duration_seconds_count{job=\"forwarder\"}[$__rate_interval])\n    )\n  )[1m:]\n)",
     "legendFormat": "Jitter {{cluster}}"
    }
   ]
  },
  {
   "title": "PDNS - UDP - IPv4 - All Clusters",
   "type": "stat",
   "description": "Authoritative Server Received QPS",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(pdns_auth_udp4_queries{job=\"pdns\"}[$__rate_interval])",
     "legendFormat": "QPS {{cluster}}"
    }
   ]
  },
  {
   "title": "PDNS - UDP - IPv4 - All Clusters",
   "type": "timeseries",
   "description": "Authoritative Server Received QPS",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 56 },
   "targets": [
    {
     "expr": "rate(pdns_auth_udp4_queries{job=\"pdns\"}[1m])",
     "legendFormat": "QPS {{cluster}}"
    }
   ]
  },
  {
   "title": "AC - Auth DNS Latency Avergage ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 56 },
   "targets": [
    {
     "expr": "avg by (cluster) (pdns_auth_latency{ role=\"auth-dns-server\"})",
     "legendFormat": "Avg Latency {{cluster}} ms"
    }
   ]
  },
  {
   "title": "Authoritative DNS Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 56 },
   "targets": [
    {
     "expr": "stddev_over_time(\n  (\n    sum by (cluster) (\n      rate(pdns_auth_backend_latency[$__rate_interval])\n    )\n  )[1m:]\n)",
     "legendFormat": "Jitter {{cluster}}"
    }
   ]
  },
  {
   "title": "PDNS - TCP - IPv4 - All Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(pdns_auth_tcp_queries{job=\"pdns\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pdns_Auth_backend_queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(pdns_auth_backend_queries[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}